name: accionables

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Paso 1 - Checkout repo
        uses: actions/checkout@v4

      - name: Paso 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: Paso 3 - Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -e . # Cambia esto si usas otra forma de declarar dependencias

      - name: Paso 4 - Ejecutar Main
        run: python src/main.py

      - name: Paso 5 - Guardar el commit con el último cambio desde pipeline
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Genera archivo csv de las web
          commit_user_name: Andres Callejas [GitHub Actions]
          commit_user_email: andres.callejas@example.com  # Usa tu correo real o de estudiante
          commit_author: Jhon Benitez <jhon.benitez@est.iudigital.edu.co>
